### ISSUE TITLE
Paths are too long

### ISSUE THREAD

**Issue by hauxir** [OpenBazaar/OpenBazaar-Installer#1]
The paths of sub-modules of other node_modules become too long for Windows when installing causing write errors. Just wanted to point that out.

**Comment by hauxir** [comment]
https://github.com/nodejs/node-v0.x-archive/issues/6960

**Comment by hoffmabc** [comment]
Did you experience this or just warning? I have not run into it with the default install paths but I will check it out.

**Comment by JCLengeling** [comment]
I created some screenshots of what we got; tried 2 different install paths 

![bug1](https://cloud.githubusercontent.com/assets/11597092/10168054/5727144a-66cb-11e5-952b-fa9758438528.PNG)
![bug2](https://cloud.githubusercontent.com/assets/11597092/10168057/57346898-66cb-11e5-8fa4-f38eeff36110.PNG)
![bug3](https://cloud.githubusercontent.com/assets/11597092/10168055/5732216e-66cb-11e5-9d6b-16acbf00bcb2.PNG)
![bug4](https://cloud.githubusercontent.com/assets/11597092/10168056/57340e02-66cb-11e5-9d1b-37174e7a7b9e.PNG)

**Comment by hoffmabc** [comment]
Ok looking into packaging it into an ASAR.

**Comment by hoffmabc** [comment]
This is no longer an issue in latest installer.
