### ISSUE TITLE
Server does not automatically start when opening client

### ISSUE THREAD

**Issue by stevenroose** [OpenBazaar/OpenBazaar-Installer#12]
The client is build in `temp-XXX/openbazaar-platformXXX/openbazaar`. When run, it complaints that no server can be found on the local system.

The server is build separately in `build-platformXXX/OpenBazaar-server/openbazaard`.

**Comment by hoffmabc** [comment]
I'll re-open if still an issue. Please report back @stevenroose .

**Comment by stevenroose** [comment]
@hoffmabc I'm on Arch now, so I can't test anymore.
