### ISSUE TITLE
Checksum doesn't match

### ISSUE THREAD

**Issue by TheButterZone** [OpenBazaar/OpenBazaar-Installer#22]
According to https://github.com/OpenBazaar/OpenBazaar-Installer/releases
OpenBazaar-1.0.6.dmg
721ade108dd7bc49f6068ad83097f6b24b87e9e8136d689445759c7e32636a87 

What command did you use to get THAT checksum?

shasum and openssl sha1 both spit out 
2c76fd110de6728d387d26ce920e666fb6a1d517
md5 & openssl md2&5 spit out
d76e54766be117f42c7aae710a52480e

**Comment by TheButterZone** [comment]
openssl dgst -sha256 ~/.../OpenBazaar-1.0.6.dmg

Finally matches.

**Comment by hoffmabc** [comment]
Sorry should have included the hash type
