### ISSUE TITLE
Document checksum verification

### ISSUE THREAD

**Issue by thijstriemstra** [OpenBazaar/OpenBazaar-Installer#25]
I'd like to verify the checksum of the openbazaar installer as noted on https://github.com/OpenBazaar/OpenBazaar-Installer/releases but have no idea how because it doesn't seem to be sha1 or md5. Could you add a note somewhere (on that releases page?) showing average users how to verify their installer?

**Comment by Perlover** [comment]
+1
Downloaded file OpenBazaar-1.0.6_Setup_x64.exe has SHA256 as 09fd8b896bf40e0a471d66ad9b4ff3ad7b2e3a4a60330def2dea52ea9643b935
But in your file (https://github.com/OpenBazaar/OpenBazaar-Installer/releases) it should have as b6d6eea6c9a7dcd58bec77a4cbd25c15ec57c4e75ce95cd4dc635fc5936c620e

**Comment by Perlover** [comment]
And downloaded file:
openbazaar_1.0.6_amd64.deb
92051986a773af50e0c96c4b3d2475a4420a6a661667b643f24cb6d9ddf69c20
Has same SHA256
So the Windows 64bit version has bad SHA256 checksum
Please check up it!

**Comment by jonathancross** [comment]
Release notes should say "SHA-256 Hashes" rather than "Checksums".
I have confirmed that all hashes are correct **except for** `OpenBazaar-1.0.6_Setup_x64.exe` which should be: `09fd8b896bf40e0a471d66ad9b4ff3ad7b2e3a4a60330def2dea52ea9643b935`.

**Comment by hoffmabc** [comment]
Hash updated.

**Comment by ghost** [comment]
please mention the algo used in the docs or on the download page. i had to google it to find out.

**Comment by jonathancross** [comment]
@picojoule I agree.
Older releases had info on the hashing algo, but it was omitted on newer releases.
Ideally each **Hashes** header would read **SHA256 Hashes**.
