### ISSUE TITLE
Add an automatic installation for RPi (Linux Raspberry Pi2-ARMv7) with Raspbian, please.

### ISSUE THREAD

**Issue by Nogreedy** [OpenBazaar/OpenBazaar-Installer#26]
Add an automatic installation for RPi (Linux raspberry Pi2-ARMv7) with Raspbian, please.

**Comment by Nogreedy** [comment]
@hoffmabc @drwasho @cpacia @SamPatt @jjeffryes and I think it's important because it can help to increase the number of continuously connected nodes to OpenBazaar...
Thanks.

**Comment by cpacia** [comment]
Yeah I tend to think following the manual install instructions is probably good enough here. Installing it manually is only a couple extra steps compared to just installing a binary.

**Comment by Nogreedy** [comment]
@cpacia Yes, I agree with you... manual install on my RPi2 wasn't a real problem... but installing a binary is more convenient for non-tech people...
