### ISSUE TITLE
"OpenBazaar.app" is damaged and can't be opened

### ISSUE THREAD

**Issue by CodingAnarchy** [OpenBazaar/OpenBazaar-Installer#34]
After installing the updated version (v1.1.1) using the OSX .dmg file, I'm getting an error that says the app is "damaged" whenever I try to open it.

I'm running OSX El Capitan 10.11.4.

**Comment by tyndallm** [comment]
Same for me on OSX El Capitan 10.11.1

**Comment by gartz** [comment]
confirmed here OSX El Capitain 10.11.4

**Comment by hoffmabc** [comment]
It's a signing issue that we will fix. In the meantime:

![image](https://cloud.githubusercontent.com/assets/45482/14371289/158a6418-fd04-11e5-8b7a-6b9174dadc67.png)
