### ISSUE TITLE
OpenBazaar-Installer 1.1.2 does not work as indicated.

### ISSUE THREAD

**Issue by wirion** [OpenBazaar/OpenBazaar-Installer#36]
Hi,
I wanted to install OpenBazaar. Upon running the installer, instead of going through setup (language choice etc.), there is a turning arrow, and then it shows:

![untitled](https://cloud.githubusercontent.com/assets/1149836/14411431/23a449f6-ff48-11e5-8d4b-83ee6c14e175.png)

I chose a username and password, but it just comes back with the same message, "Unable to connect to your server".

**Comment by Stefanie80** [comment]
I had the same Problem.
Install latest OpenSSL on your System, and in above window, hit the Restore defaults. Should work then.
And yes, OpenSSL is required even if you turn SSL off in above window.

**Comment by wirion** [comment]
Thanks for the suggestion Stefanie. Upon installing openssl, I managed to connect and set up everything. But now after I've quit and restarted, it refuses to connect again.

**Comment by hoffmabc** [comment]
Please make sure that it's completely closed before restarting it again. Perhaps it's still running in the background. You can check in Task Manager.

**Comment by wirion** [comment]
I did that, but unfortunately to no avail. Same for starting OpenBazaar after a cold reboot.
But if nobody else has this persistent issue, it's probably something on my system.
